services:
  db:
    image: pgvector/pgvector:pg16
  redis:
    image: redis:7-alpine
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
  companion:
    image: ghcr.io/nerdoutinc/paperless-ag:latest
  caddy:
    image: caddy:2-alpine
